import {
  Button,
  Center,
  Container,
  Flex,
  Input,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEventHandler, useState } from "react";
import { RankingCard } from "../components/RankingCard";

type Props = {
  youtuberRanking: string[];
  politicianRanking: string[];
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  // TODO: DBから取得するようにする
  const youtuberRanking = ["はじめしゃちょー", "ヒカキン", "セイキン"];
  const politicianRanking = ["麻生太郎", "菅直人", "河野太郎"];

  return {
    props: {
      youtuberRanking,
      politicianRanking,
    },
  };
};

const Home: NextPage<Props> = ({ youtuberRanking, politicianRanking }) => {
  const router = useRouter();
  const [slug, setSlug] = useState("");
  const onSubmit: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();
    router.push(`/${slug}`);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" pt="4" maxW="container.lg">
        <Center>
          <Text fontSize="24">デジタルスコアをはかってみよう</Text>
        </Center>
        <form onSubmit={onSubmit}>
          <Flex justifyItems="center">
            <Center pr="1">@</Center>
            <Input
              onChange={(e) => setSlug(e.target.value)}
              display="inline-block"
            />
            <Button type="submit" ml="4">検索</Button>
          </Flex>
        </form>

        <SimpleGrid minChildWidth="320px" gap="4" mt="4">
          <RankingCard title="Youtuber" items={youtuberRanking} />
          <RankingCard title="政治家" items={politicianRanking} />
        </SimpleGrid>
      </Container>
    </div>
  );
};

export default Home;
